changelog:
  exclude:
    labels:
      - skip-changelog
      - ignore-for-release
    authors:
      - github-actions[bot]
  categories:
    - title: Breaking Changes
      labels:
        - breaking
        - breaking-change
        - semver-major
    - title: Features
      labels:
        - feature
        - enhancement
        - semver-minor
    - title: Fixes
      labels:
        - bug
        - fix
        - semver-patch
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Maintenance
      labels:
        - chore
        - refactor
        - dependencies
        - ci
        - tests
    - title: Other Changes
      labels:
        - "*"
